platform:ios,'7.1'
#use_frameworks!

target 'ZJCommonProject' do
pod 'AFNetworking', '~> 3.0.4'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 3.0.10'
pod 'MJRefresh', '~> 2.3.2'
pod 'Masonry', '~> 0.6.2'
pod 'JSONModel', '~> 1.0.1'
pod 'FMDB/common' , '~>2.5'
pod 'FMDB/SQLCipher', '~>2.5'
pod 'CocoaLumberjack', '~> 2.0.0-rc'
pod 'RTLabel', '~> 1.0.1'
pod 'FLAnimatedImage', '~> 1.0'
pod 'LGAlertView', '~> 2.0.13'
pod 'mp3lame-for-ios', '~> 0.1.1'
end
